
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int op_resta = 32;
  public static final int cadena_simple = 30;
  public static final int Numero_decimal = 46;
  public static final int imprimir = 9;
  public static final int operadores_logicos = 13;
  public static final int fecha = 24;
  public static final int op_division = 33;
  public static final int boleano = 20;
  public static final int op_suma = 31;
  public static final int t_byte = 27;
  public static final int corchete_cerrado = 44;
  public static final int coma = 36;
  public static final int nulo = 15;
  public static final int contrario_si = 4;
  public static final int punto_y_coma = 37;
  public static final int boleana = 10;
  public static final int llave_cerrada = 42;
  public static final int caracter = 21;
  public static final int lista = 22;
  public static final int fechahora = 26;
  public static final int par_abierto = 39;
  public static final int si = 3;
  public static final int op_multiplicacion = 35;
  public static final int EOF = 0;
  public static final int comillas = 45;
  public static final int error = 1;
  public static final int op_asignacion = 34;
  public static final int corchete_abierto = 43;
  public static final int entero = 16;
  public static final int Reservada = 8;
  public static final int hora = 25;
  public static final int funcion = 6;
  public static final int ERROR = 48;
  public static final int PRINCIPIO = 2;
  public static final int operadores_comparacion = 14;
  public static final int llave_abierta = 41;
  public static final int incremento = 11;
  public static final int Identificador = 28;
  public static final int decremento = 12;
  public static final int comentario = 38;
  public static final int retornar = 7;
  public static final int Numero = 47;
  public static final int mapa = 23;
  public static final int flotante = 18;
  public static final int decimal = 19;
  public static final int cadena_literal = 29;
  public static final int par_cerrado = 40;
  public static final int contrario = 5;
  public static final int cadena = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINCIPIO",
  "si",
  "contrario_si",
  "contrario",
  "funcion",
  "retornar",
  "Reservada",
  "imprimir",
  "boleana",
  "incremento",
  "decremento",
  "operadores_logicos",
  "operadores_comparacion",
  "nulo",
  "entero",
  "cadena",
  "flotante",
  "decimal",
  "boleano",
  "caracter",
  "lista",
  "mapa",
  "fecha",
  "hora",
  "fechahora",
  "t_byte",
  "Identificador",
  "cadena_literal",
  "cadena_simple",
  "op_suma",
  "op_resta",
  "op_division",
  "op_asignacion",
  "op_multiplicacion",
  "coma",
  "punto_y_coma",
  "comentario",
  "par_abierto",
  "par_cerrado",
  "llave_abierta",
  "llave_cerrada",
  "corchete_abierto",
  "corchete_cerrado",
  "comillas",
  "Numero_decimal",
  "Numero",
  "ERROR"
  };
}

